### ISSUE TITLE
plugin file missing?

### ISSUE THREAD

**Issue by jbraem** [ichik/RemoveAllGuides#6]
I downloaded your package and it doesn't seem to include a .sketchplugin file.

Am I missing something?

Cheers, Justin

**Comment by ichik** [comment]
Where did you download it from? https://github.com/ichik/RemoveAllGuides/releases/latest is a proper link. Archive only contains a .sketchplugin file.

**Comment by jbraem** [comment]
I just downloaded the .zip from that link, and here are the contents:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/360540/59529688-4d5af500-8ea7-11e9-8e85-c921c571dbfa.png">

**Comment by ichik** [comment]
You're downloading source code from the looks of it. Use the first link:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/80973/59529841-6208ae80-8ee2-11e9-9348-5ca477b3f024.png">

**Comment by jbraem** [comment]
Haha, sorry. I'm dumb.

Let's just pretend this never happened....

**Comment by ichik** [comment]
No worries.
